-- AlterTable
ALTER TABLE "Equipe1" ALTER COLUMN "asWin" DROP NOT NULL,
ALTER COLUMN "asWin" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Equipe2" ALTER COLUMN "asWin" DROP NOT NULL,
ALTER COLUMN "asWin" DROP DEFAULT;
